package ban.model.persistence;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * Created by bnorrish on 7/9/15.
 */
@DynamoDBTable(tableName="Event")
public class EventD {

  @DynamoDBAutoGeneratedKey
  @DynamoDBHashKey(attributeName="EventId")
  private String eventId;

  @DynamoDBAttribute(attributeName="Name")
  private String name;

  @DynamoDBAttribute(attributeName="IsWsdcPointed")
  private boolean isWsdcPointed;

  @DynamoDBAttribute(attributeName="EventDate")
  private String eventDate;

  public String getEventId() {
    return eventId;
  }

  public void setEventId(String eventId) {
    this.eventId = eventId;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public boolean isWsdcPointed() {
    return isWsdcPointed;
  }

  public void setIsWsdcPointed(boolean isWsdcPointed) {
    this.isWsdcPointed = isWsdcPointed;
  }

  public String getEventDate() {
    return eventDate;
  }

  public void setEventDate(String eventDate) {
    this.eventDate = eventDate;
  }
}
