package ban.model.persistence;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMarshalling;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Set;

/**
 * Created by bnorrish on 9/14/15.
 */
@DynamoDBTable(tableName="FlaggedVideo")
public class FlaggedVideoD {

  @DynamoDBAutoGeneratedKey
  @DynamoDBHashKey(attributeName="FlagId")
  private String flagId;

  @DynamoDBAttribute(attributeName="FlaggedVideoId")
  private String flaggedVideoId;

  @DynamoDBAttribute(attributeName="ProviderId")
  private Integer providerId;

  @DynamoDBAttribute(attributeName="ProviderVideoId")
  private String providerVideoId;

  @DynamoDBAttribute(attributeName="Title")
  private String title;

  @DynamoDBAttribute(attributeName="DancerIdList")
  private Set<Integer> dancerIdList;

  @DynamoDBAttribute(attributeName="EventId")
  private String eventId;

  @DynamoDBAttribute(attributeName="Explanation")
  private String explanation;

  @DynamoDBAttribute(attributeName = "SkillLevel")
  @DynamoDBMarshalling(marshallerClass = SkillLevelConverter.class)
  private SkillLevel skillLevel;

  public String getFlagId() {
    return flagId;
  }

  public void setFlagId(String flagId) {
    this.flagId = flagId;
  }

  public String getFlaggedVideoId() {
    return flaggedVideoId;
  }

  public void setFlaggedVideoId(String flaggedVideoId) {
    this.flaggedVideoId = flaggedVideoId;
  }

  public Integer getProviderId() {
    return providerId;
  }

  public void setProviderId(Integer providerId) {
    this.providerId = providerId;
  }

  public String getProviderVideoId() {
    return providerVideoId;
  }

  public void setProviderVideoId(String providerVideoId) {
    this.providerVideoId = providerVideoId;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Set<Integer> getDancerIdList() {
    return dancerIdList;
  }

  public void setDancerIdList(Set<Integer> dancerIdList) {
    this.dancerIdList = dancerIdList;
  }

  public String getEventId() {
    return eventId;
  }

  public void setEventId(String eventId) {
    this.eventId = eventId;
  }

  public String getExplanation() {
    return explanation;
  }

  public void setExplanation(String explanation) {
    this.explanation = explanation;
  }

  public SkillLevel getSkillLevel() {
    return skillLevel;
  }

  public void setSkillLevel(SkillLevel skillLevel) {
    this.skillLevel = skillLevel;
  }
}
